export const TABLE_OPTIONS = [
  { display: 'Allergen Information', actual: 'allergen_information' },
  { display: 'Customer Address', actual: 'customer_address' },
  { display: 'Customer Payments', actual: 'customer_payments' },
  { display: 'Customers', actual: 'customers' },
  { display: 'Expired Items', actual: 'expired_items' },
  { display: 'General Ledger', actual: 'general_ledger' },
  { display: 'Image Locations', actual: 'image_locations' },
  { display: 'Interest Charges', actual: 'interest_charges' },
  { display: 'Invoiced Items', actual: 'invoiced_items' },
  { display: 'Invoices', actual: 'invoices' },
  { display: 'Items', actual: 'items' },
  { display: 'Nutrition Information', actual: 'nutrition_info' },
  { display: 'Offers', actual: 'offers' },
  { display: 'Page Section Text', actual: 'page_section_text' },
  { display: 'Page Sections', actual: 'page_sections' },
  { display: 'Payments', actual: 'payments' },
  { display: 'Retail Item Images', actual: 'retail_item_images' },
  { display: 'Retail Users', actual: 'retail_users' },
  { display: 'Stocked Items', actual: 'stocked_items' },
  { display: 'Supplier Invoices', actual: 'supplier_invoices' },
  { display: 'Suppliers', actual: 'suppliers' },
  { display: 'Users', actual: 'users' },
  { display: 'Warehouse', actual: 'warehouse' },
];
