import {
  faAddressBook,
  faArrowDown,
  faArrowLeft,
  faArrowsLeftRight,
  faArrowUp,
  faBasketShopping,
  faBookMedical,
  faBookOpen,
  faBox,
  faCopy,
  faFileInvoice,
  faFilter,
  faLock,
  faLockOpen,
  faNoteSticky,
  faPencil,
  faPlus,
  faPrint,
  faSearch,
  faSpinner,
  faTrashCan,
  faTruckFront,
  faUserLock,
  faX,
} from '@fortawesome/free-solid-svg-icons';

export const TABLE_ICONS = {
  userLock: faUserLock,
  addressBook: faAddressBook,
  box: faBox,
  lock: faLock,
  lockOpen: faLockOpen,
  shoppingBasket: faBasketShopping,
  spinner: faSpinner,
  pencil: faPencil,
  search: faSearch,
  print: faPrint,
  bin: faTrashCan,
  filter: faFilter,
  x: faX,
  arrowLeftRight: faArrowsLeftRight,
  arrowLeft: faArrowLeft,
  arrowUp: faArrowUp,
  arrowDown: faArrowDown,
  medicalBook: faBookMedical,
  openBook: faBookOpen,
  truck: faTruckFront,
  copy: faCopy,
  stickyNote: faNoteSticky,
  fileInvoice: faFileInvoice,
  plus: faPlus,
};
